<?php 

require __DIR__ . '/appengine-https.php';

  // Initiate the autoloader. The file should be generated by Composer.
  // You will provide your own autoloader or require the files directly if you did
  // not install via Composer.
  require_once __DIR__ . '/recaptcha/src/autoload.php';

  // Register API keys at https://www.google.com/recaptcha/admin
  $siteKey = 'reCAPTCHA_site_key'; // Replace your reCAPTCHA_site_key
  $secret = 'Secret_Key'; // Replace your Secret_Key

  // Copy the config.php.dist file to config.php and update it with your keys to run the examples
  if ($siteKey == '' && is_readable(__DIR__ . '/recaptcha/config.php')) {
      $config = include __DIR__ . '/recaptcha/config.php';
      $siteKey = $config['v3']['site'];
      $secret = $config['v3']['secret'];
  }

  // Effectively we're providing an API endpoint here that will accept the token, verify it, and return the action / score to the page
  // In production, always sanitize and validate the input you retrieve from the request.
  $recaptcha = new \ReCaptcha\ReCaptcha($secret);
  $resp = $recaptcha->setExpectedHostname($_SERVER['SERVER_NAME'])
                    ->setExpectedAction($_GET['action'])
                    ->setScoreThreshold(0.5)
                    ->verify($_POST['response'], $_SERVER['REMOTE_ADDR']);
  header('Content-type:application/json');
  echo json_encode($resp->toArray());

?>